---
Description: SNS Topic for the notification configuration of alarms created by the amazon-cloudwatch-auto-alarms Lambda function
AWSTemplateFormatVersion: '2010-09-09'
#Parameters:
#  OrganizationID:
#    Description: Provide read access to all accounts in the organization.  Leave blank for single account S3 bucket permissions.
#    Type: String
#    Default: ""
#Conditions:
#  OrgEnabledAccess: !Not [!Equals ["", !Ref OrganizationID]]

Resources:
  CloudWatchEC2AutoAlarmsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: CloudWatchEC2AutoAlarms SNS Notification Topic
      TopicName: CloudWatchEC2AutoAlarmsSNSTopic


  CloudWatchEC2AutoAlarmsSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CloudWatchEC2AutoAlarmsSNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Id: SSEAndSSLPolicy
        Statement:
          - Sid: Allow_Publish_Alarms
            Effect: Allow
            Principal:
              Service:
                - cloudwatch.amazonaws.com
            Action: sns:Publish
            Resource:
              - !Join
                - ':'
                - - 'arn'
                  - !Ref AWS::Partition
                  - 'sns'
                  - !Ref AWS::Region
                  - !Ref AWS::AccountId
                  - !GetAtt CloudWatchEC2AutoAlarmsSNSTopic.TopicName

Outputs:
  CloudWatchEC2AutoAlarmsSNSTopicArn:
    Value: !Ref CloudWatchEC2AutoAlarmsSNSTopic
    Description: "SNS topic for notifications for alarms created by the CloudWatchEC2AutoAlarms lambda function"
    Export:
      Name: !Sub "amazon-cloudwatch-auto-alarms-sns-topic-arn"
